const strings: Record<string, Record<string, string>> = {
  en: {
    onboarding_detect_title: "Detects what's around you",
    onboarding_detect_subtitle: 'Objects, distances, and obstacles',
    onboarding_detect_tts: "EYES detects objects, distances, and obstacles around you using your phone's camera.",
    onboarding_how_title: 'Point → Tap → Listen',
    onboarding_how_subtitle: 'Simple three-step interaction',
    onboarding_how_tts: 'Point your camera at your surroundings. Tap the analyze button. Listen to the spoken result.',
    onboarding_feedback_title: 'Multiple Feedback Types',
    onboarding_feedback_subtitle: 'Voice and Vibration',
    onboarding_feedback_tts: 'Get feedback through voice descriptions and vibration patterns.',
    onboarding_privacy_title: 'Your privacy is protected',
    onboarding_privacy_subtitle: 'No images are saved or stored',
    onboarding_privacy_tts: 'Your privacy matters. No images are saved or stored on this device or any server.',
    skip: 'Skip',
    get_started: 'Get Started',
    next: 'Next',
    camera_ready: 'Camera ready. Tap to analyze.',
    analyzing: 'Analyzing your surroundings',
    starting_camera: 'Starting camera...',
    camera_unavailable: 'Camera unavailable',
    check_permissions: 'Please check camera permissions',
    last_result: 'Last:',
    auto_on: 'Auto: ON',
    auto: 'Auto',
    settings: 'Settings',
    appearance: 'APPEARANCE',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    feedback: 'FEEDBACK',
    voice_feedback: 'Voice Feedback',
    vibration_feedback: 'Vibration Feedback',
    vibration_intensity: 'Vibration Intensity',
    light_intensity: 'Light',
    medium_intensity: 'Medium',
    strong_intensity: 'Strong',
    speech_rate: 'Speech Rate',
    scanning: 'SCANNING',
    auto_scan: 'Auto-Scan',
    scan_interval: 'Scan Interval',
    general: 'GENERAL',
    language: 'Language',
    english: 'English',
    filipino: 'Filipino',
    history: 'History',
    about: 'ABOUT',
    about_eyes: 'About EYES',
    version: 'Version',
    disable_voice_title: 'Disable Voice?',
    disable_voice_message: 'Voice is your primary feedback method. Are you sure?',
    cancel: 'Cancel',
    turn_off: 'Turn Off',
    about_title: 'About EYES',
    purpose: 'Purpose',
    technology: 'Technology',
    disclaimer: 'Disclaimer',
    developers: 'Developers',
    made_with_purpose: 'Made with purpose.',
    institution: 'Institution',
    created_by: 'Created by',
    app_info: 'APP INFO',
    thesis_project: 'Undergraduate Thesis Project',
    error_timeout: 'Request timed out. Please try again.',
    error_no_internet: 'No internet connection.',
    error_generic: 'Something went wrong. Please try again.',
    voice_listening: 'Voice active',
    voice_not_supported: 'Voice commands not supported in this browser.',
    intro_response: 'I am EYES, an AI-powered vision assistance app. I can detect objects around you, estimate their distance, and identify obstacles. I can also recognize Philippine currency. Point your camera and tap the analyze button, or simply say capture to scan your surroundings. I provide voice feedback and vibration alerts to keep you safe.',
    voice_capture_heard: 'Capturing now.',
    continue_scanning: 'Continue Scanning',
    currency_detected: 'Currency Detected',
    away: 'away',
    objects_detected: 'objects detected',
    object_detected: 'object detected',
  },
  fil: {
    onboarding_detect_title: 'Nakaka-detect ng paligid mo',
    onboarding_detect_subtitle: 'Mga bagay, distansya, at hadlang',
    onboarding_detect_tts: 'Ang EYES ay nakaka-detect ng mga bagay, distansya, at hadlang sa iyong paligid gamit ang camera ng iyong telepono.',
    onboarding_how_title: 'Itutok → I-tap → Makinig',
    onboarding_how_subtitle: 'Simpleng tatlong hakbang',
    onboarding_how_tts: 'Itutok ang camera sa iyong paligid. I-tap ang analyze button. Makinig sa resulta.',
    onboarding_feedback_title: "Iba't ibang Uri ng Feedback",
    onboarding_feedback_subtitle: 'Boses at Vibration',
    onboarding_feedback_tts: 'Makakuha ng feedback sa pamamagitan ng paglalarawan ng boses at pattern ng vibration.',
    onboarding_privacy_title: 'Protektado ang iyong privacy',
    onboarding_privacy_subtitle: 'Walang mga litratong nai-save',
    onboarding_privacy_tts: 'Mahalaga ang iyong privacy. Walang mga litratong nai-save o naka-store sa device o sa anumang server.',
    skip: 'Laktawan',
    get_started: 'Magsimula',
    next: 'Susunod',
    camera_ready: 'Handa na ang camera. I-tap para suriin.',
    analyzing: 'Sinusuri ang iyong paligid',
    starting_camera: 'Binubuksan ang camera...',
    camera_unavailable: 'Hindi available ang camera',
    check_permissions: 'Pakisuri ang mga camera permission',
    last_result: 'Huling:',
    auto_on: 'Auto: ON',
    auto: 'Auto',
    settings: 'Mga Setting',
    appearance: 'HITSURA',
    theme: 'Tema',
    light: 'Maliwanag',
    dark: 'Madilim',
    system: 'Sistema',
    feedback: 'FEEDBACK',
    voice_feedback: 'Voice Feedback',
    vibration_feedback: 'Vibration Feedback',
    vibration_intensity: 'Lakas ng Vibration',
    light_intensity: 'Mahina',
    medium_intensity: 'Katamtaman',
    strong_intensity: 'Malakas',
    speech_rate: 'Bilis ng Pagsasalita',
    scanning: 'PAG-SCAN',
    auto_scan: 'Auto-Scan',
    scan_interval: 'Agwat ng Scan',
    general: 'PANGKALAHATAN',
    language: 'Wika',
    english: 'Ingles',
    filipino: 'Filipino',
    history: 'Kasaysayan',
    about: 'TUNGKOL SA',
    about_eyes: 'Tungkol sa EYES',
    version: 'Bersyon',
    disable_voice_title: 'I-disable ang Voice?',
    disable_voice_message: 'Ang voice ang pangunahing paraan ng feedback. Sigurado ka ba?',
    cancel: 'Kanselahin',
    turn_off: 'Patayin',
    about_title: 'Tungkol sa EYES',
    purpose: 'Layunin',
    technology: 'Teknolohiya',
    disclaimer: 'Disclaimer',
    developers: 'Mga Developer',
    made_with_purpose: 'Ginawa nang may layunin.',
    institution: 'Institusyon',
    created_by: 'Nilikha ni',
    app_info: 'IMPORMASYON NG APP',
    thesis_project: 'Proyektong Pang-undergraduate na Tesis',
    error_timeout: 'Nag-timeout ang request. Pakisubukang muli.',
    error_no_internet: 'Walang koneksyon sa internet.',
    error_generic: 'May nangyaring mali. Pakisubukang muli.',
    voice_listening: 'Aktibo ang boses',
    voice_not_supported: 'Hindi sinusuportahan ng browser na ito ang voice commands.',
    intro_response: 'Ako si EYES, isang AI-powered na app para sa tulong sa paningin. Kaya kong mag-detect ng mga bagay sa paligid mo, tantiyahin ang kanilang distansya, at tukuyin ang mga hadlang. Kaya ko ring kumilala ng Philippine currency. Itutok ang camera mo at i-tap ang analyze button, o sabihin lang capture para i-scan ang paligid mo. Nagbibigay ako ng voice feedback at vibration alerts para sa iyong kaligtasan.',
    voice_capture_heard: 'Kumukuha na.',
    continue_scanning: 'Magpatuloy sa Pag-scan',
    currency_detected: 'May Nakitang Pera',
    away: 'ang layo',
    objects_detected: 'bagay ang nakita',
    object_detected: 'bagay ang nakita',
  },
};

export function t(key: string, language: string): string {
  return strings[language]?.[key] ?? strings['en']?.[key] ?? key;
}
